################################################################################
# \file bsp.mk
#
################################################################################
# \copyright
# Copyright 2018-2023 Cypress Semiconductor Corporation (an Infineon company) or
# an affiliate of Cypress Semiconductor Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Any additional components to apply when using this board.

# Any additional defines to apply when using this board.

################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################

# Board device selection. MPN_LIST tracks what was selected in the BSP Assistant
# All other variables are derived by BSP Assistant based on the MPN_LIST.
MPN_LIST:=XMC1100-Q024x0032
DEVICE:=XMC1100-Q024x0032
DEVICE_COMPONENTS:=CAT3 XMC11XX
DEVICE_LIST:=XMC1100-Q024x0032
DEVICE_TOOL_IDS:=bsp-assistant device-configurator library-manager memory-analyzer online-simulator project-creator
DEVICE_XMC1100-Q024x0032_CORES:=CORE_NAME_CM0_0
DEVICE_XMC1100-Q024x0032_DIE:=XMC1100
DEVICE_XMC1100-Q024x0032_FLASH_KB:=32
DEVICE_XMC1100-Q024x0032_IPBLOCKS:=XMC1_SCU XMC1_SCU_V1 XMC_CCU4 XMC_CCU4_V2 XMC_CPUSS XMC_CPUSS_V1 XMC_ERU XMC_ERU_V1 XMC_FLASH XMC_FLASH_V1 XMC_IOSS XMC_IOSS_V1 XMC_PAU XMC_PAU_V1 XMC_PRNG XMC_PRNG_V1 XMC_RTC XMC_RTC_V1 XMC_USIC XMC_USIC_V1 XMC_VADC XMC_VADC_V1 XMC_WDT XMC_WDT_V1
DEVICE_XMC1100-Q024x0032_SRAM_KB:=16
RECIPE_DIR:=$(SEARCH_recipe-make-cat3)
